name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: d41d09e761f58767a0b32bbda34bb691
          TIMEZONE: Asia/Taipei
